name: hexo deploy
on:
  # 只要不是主分支,push  上去了就和 master 分支合并
  # 每篇博客文章单开一个分支
  [push]

jobs: 
  deploy_job:
    runs-on: ubuntu-latest
    steps: 
    - name: s1
        # 把 代码库迁出到 GitHub action 的虚拟机 ubuntu-latest
        uses: actions/checkout@v1
    - name: s2  
        # 安装v16.4.2 的node
        uses: actions/setup-node@v3
        with:
          node-version: 'v16.4.2'  
    - name: s3
         if: ${{ github.ref == 'refs/heads/main' }}
         run:  echo  "dddddd" 
       

        
        





     
